### ISSUE TITLE
chi-squared analysis - prioritization guideance

### ISSUE THREAD

**Issue by andrewrfreed** [watson-developer-cloud/assistant-skill-analysis#11]
The chi-squared analysis is wonderful and I love how it does an "in place" analysis of training data without any input from the user.

Is there any way to improve consumability and next steps for this report?
Such as:
- a visualization of strongest correlated terms
- a narrowing down of the list (ie only show for worst-performing intents in some metric ie k-folds)

I tested with a workspace containing 60 intents and it gets fatiguing quickly to scan all of them.  I do understand that user input is required to find terms that "do not belong" but it would be helpful to make the task a little easier.

**Comment by haodeqi** [comment]
issue closed and we will revisit if necessary.
