### ISSUE TITLE
Need a way to disable SSL checking in calls to Skills_Util.py

### ISSUE THREAD

**Issue by dtoczala** [watson-developer-cloud/assistant-skill-analysis#21]
I have a customer using the skills_util package, that needs to do the retrieve_workspace function with SSL checking disabled.

In the retrieve_workspace function, there should be an option to disable_SLL, and the IAM Authentication would look like this when a user wants to do so with no SSL:
`authenticator = IAMAuthenticator(apikey=iam_apikey, disable_ssl_verification=True)`

**Comment by haodeqi** [comment]
Hi @dtoczala,  Thanks for brining the issue. I will make an update!

**Comment by haodeqi** [comment]
closed as the issue is fixed
