### ISSUE TITLE
Kernel error, ImportError: DLL load failed while importing win32api

### ISSUE THREAD

**Issue by Krogsager** [watson-developer-cloud/assistant-skill-analysis#32]
When I try to run skill_analysis.ipynb, I get the import error
`ImportError: DLL load failed while importing win32api`.
I'm on windows 10, and I've installed requirements.txt.

**Comment by haodeqi** [comment]
hey @Krogsager , this issue seems specific to your environment. I find a discussion of several potential solutions to it.https://stackoverflow.com/questions/58612306/how-to-fix-importerror-dll-load-failed-while-importing-win32api

**Comment by Krogsager** [comment]
Downgraded to Python 3.7 from 3.8
