### ISSUE TITLE
Defect/Code Issue while running classic_dialog_skill_analysis.ipynb

### ISSUE THREAD

**Issue by dmonisankar** [watson-developer-cloud/assistant-skill-analysis#57]
While I am trying to run this notebook, I am getting error in below mentioned code ...
`unigram_intent_dict, bigram_intent_dict = chi2_analyzer.get_chi2_analysis(workspace_pd, lang_util=lang_util)`
I could fix this issue, by making below mentioned modification in `assistant_skill_analysis/term_analysis/chi2_analyzer.py`
![image](https://user-images.githubusercontent.com/35489134/228239110-39b8d980-93df-4550-a8a2-6cb901e90673.png)

Another error while trying to execute `keyword_analyzer.py`. This would be fixed by below mentioned code change ..

![image](https://user-images.githubusercontent.com/35489134/228239890-ab665e4d-4cf0-41c6-96a4-052d537ece4e.png)

**Comment by haodeqi** [comment]
thanks for reporting the issue. It's fixed in the latest version.
