### ISSUE TITLE
nbconvert - Module not found errors

### ISSUE THREAD

**Issue by axl-github-azure-2023** [watson-developer-cloud/assistant-skill-analysis#59]
I tried to run on Python 3.10 Kernel in CloudPak - script stopped in step 3 complaining about a missing module: `nbconvert`.

`!pip list` revealed an outdated version of the module (5), so we installed the latest per 2023-07:

```
!pip install --index-url https://pypi.python.org/simple  -U "nbconvert>=7.7.1"
```

This fixed the issues.

**Comment by haodeqi** [comment]
Hi @axl-github-azure-2023 , thanks for reporting the issue. We will make an update.
