### ISSUE TITLE
Correlation analysis 1.4

### ISSUE THREAD

**Issue by aa13296** [watson-developer-cloud/assistant-skill-analysis#61]
Classic dialog skill analysis - got up to 1.4 when running the notebook and encountered this error: 
InvalidParameterError: The 'stop_words' parameter of CountVectorizer must be a str among {'english'}, an instance of 'list' or None. Got {'i', 'the', 'of', 'and', 'is', 'or', 'be', 'in', 'a', 'an', 'to', 'on', 'can'} instead.

**Comment by haodeqi** [comment]
closed as issue already addressed
