### ISSUE TITLE
error when running keyword_analyzer

### ISSUE THREAD

**Issue by michalkordyzon** [watson-developer-cloud/assistant-skill-analysis#62]
When running on action skill following code:
`keyword_analyzer.seaborn_heatmap(workspace_pd, lang_util, 30, 30, intent_list)`

 I get error message from keyword_analyzer:
`KeyError: 'n_w'`

**Comment by michalkordyzon** [comment]
full error message:
`File ~/_dev/assistant-skill-analysis-master/assistant_skill_analysis/term_analysis/keyword_analyzer.py:104, in seaborn_heatmap(workspace_df, lang_util, label_for_display, max_token_display, class_list)
     94 def seaborn_heatmap(
     95     workspace_df, lang_util, label_for_display=30, max_token_display=30, class_list=None
     96 ):
     97     """
     98     Create heat map of word frequencies per intent
     99     :param workspace_df:
   (...)
    102     :param class_list:
    103     """
--> 104     counts, top_counts = _preprocess_for_heat_map(
    105         workspace_df, lang_util, label_for_display, max_token_display, class_list
    106     )
    107     reset_groupby = counts.reset_index()
    108     most_frequent_words = top_counts.reset_index()["word"].unique()

File ~/_dev/assistant-skill-analysis-master/assistant_skill_analysis/term_analysis/keyword_analyzer.py:44, in _preprocess_for_heat_map(workspace_df, lang_util, label_for_display, max_token_display, class_list)
     37         counts = _get_counts_per_label(
     38             workspace_df, lang_util=lang_util, unigrams_col_name="unigrams"
     39         )
     41 max_n = int(
     42     np.ceil(max_token_display / len(counts.index.get_level_values(0).unique()))
     43 )
---> 44 top_counts = _get_top_n(counts["n_w"], top_n=max_n)
     45 return counts, top_counts

File ~/anaconda3/envs/wa/lib/python3.10/site-packages/pandas/core/frame.py:3761, in DataFrame.__getitem__(self, key)
   3759 if self.columns.nlevels > 1:
   3760     return self._getitem_multilevel(key)
-> 3761 indexer = self.columns.get_loc(key)
   3762 if is_integer(indexer):
   3763     indexer = [indexer]

File ~/anaconda3/envs/wa/lib/python3.10/site-packages/pandas/core/indexes/base.py:3655, in Index.get_loc(self, key)
   3653     return self._engine.get_loc(casted_key)
   3654 except KeyError as err:
-> 3655     raise KeyError(key) from err
   3656 except TypeError:
   3657     # If we have a listlike key, _check_indexing_error will raise
   3658     #  InvalidIndexError. Otherwise we fall through and re-raise
   3659     #  the TypeError.
   3660     self._check_indexing_error(key)

KeyError: 'n_w'`

**Comment by haodeqi** [comment]
hi @michalkordyzon , this should be fixed in the latest version.
