### ISSUE TITLE
404 saying resource not found  for Assistant skill analysis in Watson Studio

### ISSUE THREAD

**Issue by sheldonfernandes** [watson-developer-cloud/assistant-skill-analysis#67]
We are trying to configure the Assistant skill analysis  [hosted notebook](
https://dataplatform.cloud.ibm.com/exchange/public/entry/view/4d77701840fcb2f21587e39fdb887049) to work with our Watson Assistant. It however  fails with  a 404 Resource not found  error in Watson Studio

`ApiException: Error: Resource not found, Code: 404 , X-global-transaction-id: 75434a3e-9c9b-4857-b662-bf1b44c98cff`

Full error below
![Screenshot 2024-01-04 at 10 48 17 AM](https://github.com/watson-developer-cloud/assistant-skill-analysis/assets/7300877/cc0dd1b8-6eba-4dbf-8f11-fc9803654cbc)

**Comment by muktika1** [comment]
Im having the same issue!

**Comment by muktika1** [comment]
i figured out the issue, that is the old classic assistant thats why it isnt working, run the new version and it will work fine!

**Comment by haodeqi** [comment]
closed as no more pending issue
